# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "18.15.0"
#       - name: Install Dependencies
#         run: npm ci
#       - name: Build Project
#         run: npm run build
#       - name: FTP Deploy
#         uses: SamKirkland/FTP-Deploy-Action@4.0.0
#         with:
#           server: ${{ secrets.serverhost }}
#           username: ${{ secrets.username }}
#           password: ${{ secrets.password }}
#           protocol: ftps
#           server-dir: /htdocs/website/
#           local-dir: ./dist/
#       - name: Catch step
#         if: failure()
#         run: echo "The job has failed."
